"""add cloud account sync metadata

Revision ID: 076d1fd69aee
Revises: a25abb0101c0
Create Date: 2026-08-02 22:55:53.840750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076d1fd69aee'
down_revision: Union[str, Sequence[str], None] = 'a25abb0101c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_accounts', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cloud_accounts', sa.Column('last_sync_region', sa.String(length=30), nullable=True))
    op.add_column('cloud_accounts', sa.Column('last_sync_status', sa.String(length=20), nullable=True))
    op.add_column('cloud_accounts', sa.Column('resource_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_accounts', 'resource_count')
    op.drop_column('cloud_accounts', 'last_sync_status')
    op.drop_column('cloud_accounts', 'last_sync_region')
    op.drop_column('cloud_accounts', 'last_sync_at')
    # ### end Alembic commands ###
