"""create findings table

Revision ID: 17e21024f3aa
Revises: 44d4c912b2dd
Create Date: 2026-07-17 16:33:47.912709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e21024f3aa'
down_revision: Union[str, Sequence[str], None] = '44d4c912b2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cloud_account_id', sa.UUID(), nullable=False),
    sa.Column('cloud_resource_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('estimated_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cloud_resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_cloud_account_id'), 'findings', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_findings_cloud_resource_id'), 'findings', ['cloud_resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_cloud_resource_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cloud_account_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
