"""create cloud resources table

Revision ID: 44d4c912b2dd
Revises: a0f187d33dcb
Create Date: 2026-07-17 15:51:15.811987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44d4c912b2dd'
down_revision: Union[str, Sequence[str], None] = 'a0f187d33dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cloud_account_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_resources_cloud_account_id'), 'cloud_resources', ['cloud_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_resources_cloud_account_id'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    # ### end Alembic commands ###
