"""add external id to cloud accounts

Revision ID: a25abb0101c0
Revises: 17e21024f3aa
Create Date: 2026-07-17 21:30:07.982523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25abb0101c0'
down_revision: Union[str, Sequence[str], None] = '17e21024f3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_accounts', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'cloud_accounts', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cloud_accounts', type_='unique')
    op.drop_column('cloud_accounts', 'external_id')
    # ### end Alembic commands ###
